### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by tksarah** [muddydixon/ansibrest#1]
I saw an error when I tried below;

```
root@ansible:~# ansibrest -h

/usr/local/lib/node_modules/ansibrest/lib/server.js:4
const http = require("http");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
root@ansible:~# node -v
v0.10.25
root@ansible:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

Also , I saw same error message with CentOS 7 .

Any help in this regard is appreciated.

**Comment by olpia** [comment]
You have to use a recent version of nodejs, for me it works with 6.x.

**Comment by tksarah** [comment]
@agouti 
Thanks,
